/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceNapalm {
    #[serde(rename = "method")]
    pub method: serde_json::Value,
}

impl DeviceNapalm {
    pub fn new(method: serde_json::Value) -> DeviceNapalm {
        DeviceNapalm {
            method,
        }
    }
}


