/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Face {
    #[serde(rename = "label")]
    pub label: Label,
    #[serde(rename = "value")]
    pub value: Value,
}

impl Face {
    pub fn new(label: Label, value: Value) -> Face {
        Face {
            label,
            value,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Label {
    #[serde(rename = "Front")]
    Front,
    #[serde(rename = "Rear")]
    Rear,
}

impl Default for Label {
    fn default() -> Label {
        Self::Front
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Value {
    #[serde(rename = "front")]
    Front,
    #[serde(rename = "rear")]
    Rear,
}

impl Default for Value {
    fn default() -> Value {
        Self::Front
    }
}

