/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Speed {
    #[serde(rename = "label")]
    pub label: Label,
    #[serde(rename = "value")]
    pub value: i32,
}

impl Speed {
    pub fn new(label: Label, value: i32) -> Speed {
        Speed {
            label,
            value,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Label {
    #[serde(rename = "1200 bps")]
    Variant1200Bps,
    #[serde(rename = "2400 bps")]
    Variant2400Bps,
    #[serde(rename = "4800 bps")]
    Variant4800Bps,
    #[serde(rename = "9600 bps")]
    Variant9600Bps,
    #[serde(rename = "19.2 kbps")]
    Variant19Period2Kbps,
    #[serde(rename = "38.4 kbps")]
    Variant38Period4Kbps,
    #[serde(rename = "57.6 kbps")]
    Variant57Period6Kbps,
    #[serde(rename = "115.2 kbps")]
    Variant115Period2Kbps,
}

impl Default for Label {
    fn default() -> Label {
        Self::Variant1200Bps
    }
}

