/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AvailableVlan {
    #[serde(rename = "vid", skip_serializing_if = "Option::is_none")]
    pub vid: Option<i32>,
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<Box<crate::models::NestedVlanGroup>>,
}

impl AvailableVlan {
    pub fn new() -> AvailableVlan {
        AvailableVlan {
            vid: None,
            group: None,
        }
    }
}


