/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NestedL2VpnTermination {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "l2vpn")]
    pub l2vpn: Box<crate::models::NestedL2Vpn>,
}

impl NestedL2VpnTermination {
    pub fn new(l2vpn: crate::models::NestedL2Vpn) -> NestedL2VpnTermination {
        NestedL2VpnTermination {
            id: None,
            url: None,
            display: None,
            l2vpn: Box::new(l2vpn),
        }
    }
}


