/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentType {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "app_label")]
    pub app_label: String,
    #[serde(rename = "model")]
    pub model: String,
}

impl ContentType {
    pub fn new(app_label: String, model: String) -> ContentType {
        ContentType {
            id: None,
            url: None,
            display: None,
            app_label,
            model,
        }
    }
}


