/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NestedAsn {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    /// 32-bit autonomous system number
    #[serde(rename = "asn")]
    pub asn: i32,
}

impl NestedAsn {
    pub fn new(asn: i32) -> NestedAsn {
        NestedAsn {
            id: None,
            url: None,
            display: None,
            asn,
        }
    }
}


