/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NestedVirtualChassis {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "master")]
    pub master: Box<crate::models::NestedDevice>,
    #[serde(rename = "member_count", skip_serializing_if = "Option::is_none")]
    pub member_count: Option<i32>,
}

impl NestedVirtualChassis {
    pub fn new(name: String, master: crate::models::NestedDevice) -> NestedVirtualChassis {
        NestedVirtualChassis {
            id: None,
            url: None,
            display: None,
            name,
            master: Box::new(master),
            member_count: None,
        }
    }
}


