/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RfChannel {
    #[serde(rename = "label")]
    pub label: Label,
    #[serde(rename = "value")]
    pub value: Value,
}

impl RfChannel {
    pub fn new(label: Label, value: Value) -> RfChannel {
        RfChannel {
            label,
            value,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Label {
    #[serde(rename = "1 (2412 MHz)")]
    Variant1LeftParenthesis2412MhzRightParenthesis,
    #[serde(rename = "2 (2417 MHz)")]
    Variant2LeftParenthesis2417MhzRightParenthesis,
    #[serde(rename = "3 (2422 MHz)")]
    Variant3LeftParenthesis2422MhzRightParenthesis,
    #[serde(rename = "4 (2427 MHz)")]
    Variant4LeftParenthesis2427MhzRightParenthesis,
    #[serde(rename = "5 (2432 MHz)")]
    Variant5LeftParenthesis2432MhzRightParenthesis,
    #[serde(rename = "6 (2437 MHz)")]
    Variant6LeftParenthesis2437MhzRightParenthesis,
    #[serde(rename = "7 (2442 MHz)")]
    Variant7LeftParenthesis2442MhzRightParenthesis,
    #[serde(rename = "8 (2447 MHz)")]
    Variant8LeftParenthesis2447MhzRightParenthesis,
    #[serde(rename = "9 (2452 MHz)")]
    Variant9LeftParenthesis2452MhzRightParenthesis,
    #[serde(rename = "10 (2457 MHz)")]
    Variant10LeftParenthesis2457MhzRightParenthesis,
    #[serde(rename = "11 (2462 MHz)")]
    Variant11LeftParenthesis2462MhzRightParenthesis,
    #[serde(rename = "12 (2467 MHz)")]
    Variant12LeftParenthesis2467MhzRightParenthesis,
    #[serde(rename = "13 (2472 MHz)")]
    Variant13LeftParenthesis2472MhzRightParenthesis,
    #[serde(rename = "32 (5160/20 MHz)")]
    Variant32LeftParenthesis5160Slash20MhzRightParenthesis,
    #[serde(rename = "34 (5170/40 MHz)")]
    Variant34LeftParenthesis5170Slash40MhzRightParenthesis,
    #[serde(rename = "36 (5180/20 MHz)")]
    Variant36LeftParenthesis5180Slash20MhzRightParenthesis,
    #[serde(rename = "38 (5190/40 MHz)")]
    Variant38LeftParenthesis5190Slash40MhzRightParenthesis,
    #[serde(rename = "40 (5200/20 MHz)")]
    Variant40LeftParenthesis5200Slash20MhzRightParenthesis,
    #[serde(rename = "42 (5210/80 MHz)")]
    Variant42LeftParenthesis5210Slash80MhzRightParenthesis,
    #[serde(rename = "44 (5220/20 MHz)")]
    Variant44LeftParenthesis5220Slash20MhzRightParenthesis,
    #[serde(rename = "46 (5230/40 MHz)")]
    Variant46LeftParenthesis5230Slash40MhzRightParenthesis,
    #[serde(rename = "48 (5240/20 MHz)")]
    Variant48LeftParenthesis5240Slash20MhzRightParenthesis,
    #[serde(rename = "50 (5250/160 MHz)")]
    Variant50LeftParenthesis5250Slash160MhzRightParenthesis,
    #[serde(rename = "52 (5260/20 MHz)")]
    Variant52LeftParenthesis5260Slash20MhzRightParenthesis,
    #[serde(rename = "54 (5270/40 MHz)")]
    Variant54LeftParenthesis5270Slash40MhzRightParenthesis,
    #[serde(rename = "56 (5280/20 MHz)")]
    Variant56LeftParenthesis5280Slash20MhzRightParenthesis,
    #[serde(rename = "58 (5290/80 MHz)")]
    Variant58LeftParenthesis5290Slash80MhzRightParenthesis,
    #[serde(rename = "60 (5300/20 MHz)")]
    Variant60LeftParenthesis5300Slash20MhzRightParenthesis,
    #[serde(rename = "62 (5310/40 MHz)")]
    Variant62LeftParenthesis5310Slash40MhzRightParenthesis,
    #[serde(rename = "64 (5320/20 MHz)")]
    Variant64LeftParenthesis5320Slash20MhzRightParenthesis,
    #[serde(rename = "100 (5500/20 MHz)")]
    Variant100LeftParenthesis5500Slash20MhzRightParenthesis,
    #[serde(rename = "102 (5510/40 MHz)")]
    Variant102LeftParenthesis5510Slash40MhzRightParenthesis,
    #[serde(rename = "104 (5520/20 MHz)")]
    Variant104LeftParenthesis5520Slash20MhzRightParenthesis,
    #[serde(rename = "106 (5530/80 MHz)")]
    Variant106LeftParenthesis5530Slash80MhzRightParenthesis,
    #[serde(rename = "108 (5540/20 MHz)")]
    Variant108LeftParenthesis5540Slash20MhzRightParenthesis,
    #[serde(rename = "110 (5550/40 MHz)")]
    Variant110LeftParenthesis5550Slash40MhzRightParenthesis,
    #[serde(rename = "112 (5560/20 MHz)")]
    Variant112LeftParenthesis5560Slash20MhzRightParenthesis,
    #[serde(rename = "114 (5570/160 MHz)")]
    Variant114LeftParenthesis5570Slash160MhzRightParenthesis,
    #[serde(rename = "116 (5580/20 MHz)")]
    Variant116LeftParenthesis5580Slash20MhzRightParenthesis,
    #[serde(rename = "118 (5590/40 MHz)")]
    Variant118LeftParenthesis5590Slash40MhzRightParenthesis,
    #[serde(rename = "120 (5600/20 MHz)")]
    Variant120LeftParenthesis5600Slash20MhzRightParenthesis,
    #[serde(rename = "122 (5610/80 MHz)")]
    Variant122LeftParenthesis5610Slash80MhzRightParenthesis,
    #[serde(rename = "124 (5620/20 MHz)")]
    Variant124LeftParenthesis5620Slash20MhzRightParenthesis,
    #[serde(rename = "126 (5630/40 MHz)")]
    Variant126LeftParenthesis5630Slash40MhzRightParenthesis,
    #[serde(rename = "128 (5640/20 MHz)")]
    Variant128LeftParenthesis5640Slash20MhzRightParenthesis,
    #[serde(rename = "132 (5660/20 MHz)")]
    Variant132LeftParenthesis5660Slash20MhzRightParenthesis,
    #[serde(rename = "134 (5670/40 MHz)")]
    Variant134LeftParenthesis5670Slash40MhzRightParenthesis,
    #[serde(rename = "136 (5680/20 MHz)")]
    Variant136LeftParenthesis5680Slash20MhzRightParenthesis,
    #[serde(rename = "138 (5690/80 MHz)")]
    Variant138LeftParenthesis5690Slash80MhzRightParenthesis,
    #[serde(rename = "140 (5700/20 MHz)")]
    Variant140LeftParenthesis5700Slash20MhzRightParenthesis,
    #[serde(rename = "142 (5710/40 MHz)")]
    Variant142LeftParenthesis5710Slash40MhzRightParenthesis,
    #[serde(rename = "144 (5720/20 MHz)")]
    Variant144LeftParenthesis5720Slash20MhzRightParenthesis,
    #[serde(rename = "149 (5745/20 MHz)")]
    Variant149LeftParenthesis5745Slash20MhzRightParenthesis,
    #[serde(rename = "151 (5755/40 MHz)")]
    Variant151LeftParenthesis5755Slash40MhzRightParenthesis,
    #[serde(rename = "153 (5765/20 MHz)")]
    Variant153LeftParenthesis5765Slash20MhzRightParenthesis,
    #[serde(rename = "155 (5775/80 MHz)")]
    Variant155LeftParenthesis5775Slash80MhzRightParenthesis,
    #[serde(rename = "157 (5785/20 MHz)")]
    Variant157LeftParenthesis5785Slash20MhzRightParenthesis,
    #[serde(rename = "159 (5795/40 MHz)")]
    Variant159LeftParenthesis5795Slash40MhzRightParenthesis,
    #[serde(rename = "161 (5805/20 MHz)")]
    Variant161LeftParenthesis5805Slash20MhzRightParenthesis,
    #[serde(rename = "163 (5815/160 MHz)")]
    Variant163LeftParenthesis5815Slash160MhzRightParenthesis,
    #[serde(rename = "165 (5825/20 MHz)")]
    Variant165LeftParenthesis5825Slash20MhzRightParenthesis,
    #[serde(rename = "167 (5835/40 MHz)")]
    Variant167LeftParenthesis5835Slash40MhzRightParenthesis,
    #[serde(rename = "169 (5845/20 MHz)")]
    Variant169LeftParenthesis5845Slash20MhzRightParenthesis,
    #[serde(rename = "171 (5855/80 MHz)")]
    Variant171LeftParenthesis5855Slash80MhzRightParenthesis,
    #[serde(rename = "173 (5865/20 MHz)")]
    Variant173LeftParenthesis5865Slash20MhzRightParenthesis,
    #[serde(rename = "175 (5875/40 MHz)")]
    Variant175LeftParenthesis5875Slash40MhzRightParenthesis,
    #[serde(rename = "177 (5885/20 MHz)")]
    Variant177LeftParenthesis5885Slash20MhzRightParenthesis,
    #[serde(rename = "1 (5955/20 MHz)")]
    Variant1LeftParenthesis5955Slash20MhzRightParenthesis,
    #[serde(rename = "3 (5965/40 MHz)")]
    Variant3LeftParenthesis5965Slash40MhzRightParenthesis,
    #[serde(rename = "5 (5975/20 MHz)")]
    Variant5LeftParenthesis5975Slash20MhzRightParenthesis,
    #[serde(rename = "7 (5985/80 MHz)")]
    Variant7LeftParenthesis5985Slash80MhzRightParenthesis,
    #[serde(rename = "9 (5995/20 MHz)")]
    Variant9LeftParenthesis5995Slash20MhzRightParenthesis,
    #[serde(rename = "11 (6005/40 MHz)")]
    Variant11LeftParenthesis6005Slash40MhzRightParenthesis,
    #[serde(rename = "13 (6015/20 MHz)")]
    Variant13LeftParenthesis6015Slash20MhzRightParenthesis,
    #[serde(rename = "15 (6025/160 MHz)")]
    Variant15LeftParenthesis6025Slash160MhzRightParenthesis,
    #[serde(rename = "17 (6035/20 MHz)")]
    Variant17LeftParenthesis6035Slash20MhzRightParenthesis,
    #[serde(rename = "19 (6045/40 MHz)")]
    Variant19LeftParenthesis6045Slash40MhzRightParenthesis,
    #[serde(rename = "21 (6055/20 MHz)")]
    Variant21LeftParenthesis6055Slash20MhzRightParenthesis,
    #[serde(rename = "23 (6065/80 MHz)")]
    Variant23LeftParenthesis6065Slash80MhzRightParenthesis,
    #[serde(rename = "25 (6075/20 MHz)")]
    Variant25LeftParenthesis6075Slash20MhzRightParenthesis,
    #[serde(rename = "27 (6085/40 MHz)")]
    Variant27LeftParenthesis6085Slash40MhzRightParenthesis,
    #[serde(rename = "29 (6095/20 MHz)")]
    Variant29LeftParenthesis6095Slash20MhzRightParenthesis,
    #[serde(rename = "31 (6105/320 MHz)")]
    Variant31LeftParenthesis6105Slash320MhzRightParenthesis,
    #[serde(rename = "33 (6115/20 MHz)")]
    Variant33LeftParenthesis6115Slash20MhzRightParenthesis,
    #[serde(rename = "35 (6125/40 MHz)")]
    Variant35LeftParenthesis6125Slash40MhzRightParenthesis,
    #[serde(rename = "37 (6135/20 MHz)")]
    Variant37LeftParenthesis6135Slash20MhzRightParenthesis,
    #[serde(rename = "39 (6145/80 MHz)")]
    Variant39LeftParenthesis6145Slash80MhzRightParenthesis,
    #[serde(rename = "41 (6155/20 MHz)")]
    Variant41LeftParenthesis6155Slash20MhzRightParenthesis,
    #[serde(rename = "43 (6165/40 MHz)")]
    Variant43LeftParenthesis6165Slash40MhzRightParenthesis,
    #[serde(rename = "45 (6175/20 MHz)")]
    Variant45LeftParenthesis6175Slash20MhzRightParenthesis,
    #[serde(rename = "47 (6185/160 MHz)")]
    Variant47LeftParenthesis6185Slash160MhzRightParenthesis,
    #[serde(rename = "49 (6195/20 MHz)")]
    Variant49LeftParenthesis6195Slash20MhzRightParenthesis,
    #[serde(rename = "51 (6205/40 MHz)")]
    Variant51LeftParenthesis6205Slash40MhzRightParenthesis,
    #[serde(rename = "53 (6215/20 MHz)")]
    Variant53LeftParenthesis6215Slash20MhzRightParenthesis,
    #[serde(rename = "55 (6225/80 MHz)")]
    Variant55LeftParenthesis6225Slash80MhzRightParenthesis,
    #[serde(rename = "57 (6235/20 MHz)")]
    Variant57LeftParenthesis6235Slash20MhzRightParenthesis,
    #[serde(rename = "59 (6245/40 MHz)")]
    Variant59LeftParenthesis6245Slash40MhzRightParenthesis,
    #[serde(rename = "61 (6255/20 MHz)")]
    Variant61LeftParenthesis6255Slash20MhzRightParenthesis,
    #[serde(rename = "65 (6275/20 MHz)")]
    Variant65LeftParenthesis6275Slash20MhzRightParenthesis,
    #[serde(rename = "67 (6285/40 MHz)")]
    Variant67LeftParenthesis6285Slash40MhzRightParenthesis,
    #[serde(rename = "69 (6295/20 MHz)")]
    Variant69LeftParenthesis6295Slash20MhzRightParenthesis,
    #[serde(rename = "71 (6305/80 MHz)")]
    Variant71LeftParenthesis6305Slash80MhzRightParenthesis,
    #[serde(rename = "73 (6315/20 MHz)")]
    Variant73LeftParenthesis6315Slash20MhzRightParenthesis,
    #[serde(rename = "75 (6325/40 MHz)")]
    Variant75LeftParenthesis6325Slash40MhzRightParenthesis,
    #[serde(rename = "77 (6335/20 MHz)")]
    Variant77LeftParenthesis6335Slash20MhzRightParenthesis,
    #[serde(rename = "79 (6345/160 MHz)")]
    Variant79LeftParenthesis6345Slash160MhzRightParenthesis,
    #[serde(rename = "81 (6355/20 MHz)")]
    Variant81LeftParenthesis6355Slash20MhzRightParenthesis,
    #[serde(rename = "83 (6365/40 MHz)")]
    Variant83LeftParenthesis6365Slash40MhzRightParenthesis,
    #[serde(rename = "85 (6375/20 MHz)")]
    Variant85LeftParenthesis6375Slash20MhzRightParenthesis,
    #[serde(rename = "87 (6385/80 MHz)")]
    Variant87LeftParenthesis6385Slash80MhzRightParenthesis,
    #[serde(rename = "89 (6395/20 MHz)")]
    Variant89LeftParenthesis6395Slash20MhzRightParenthesis,
    #[serde(rename = "91 (6405/40 MHz)")]
    Variant91LeftParenthesis6405Slash40MhzRightParenthesis,
    #[serde(rename = "93 (6415/20 MHz)")]
    Variant93LeftParenthesis6415Slash20MhzRightParenthesis,
    #[serde(rename = "95 (6425/320 MHz)")]
    Variant95LeftParenthesis6425Slash320MhzRightParenthesis,
    #[serde(rename = "97 (6435/20 MHz)")]
    Variant97LeftParenthesis6435Slash20MhzRightParenthesis,
    #[serde(rename = "99 (6445/40 MHz)")]
    Variant99LeftParenthesis6445Slash40MhzRightParenthesis,
    #[serde(rename = "101 (6455/20 MHz)")]
    Variant101LeftParenthesis6455Slash20MhzRightParenthesis,
    #[serde(rename = "103 (6465/80 MHz)")]
    Variant103LeftParenthesis6465Slash80MhzRightParenthesis,
    #[serde(rename = "105 (6475/20 MHz)")]
    Variant105LeftParenthesis6475Slash20MhzRightParenthesis,
    #[serde(rename = "107 (6485/40 MHz)")]
    Variant107LeftParenthesis6485Slash40MhzRightParenthesis,
    #[serde(rename = "109 (6495/20 MHz)")]
    Variant109LeftParenthesis6495Slash20MhzRightParenthesis,
    #[serde(rename = "111 (6505/160 MHz)")]
    Variant111LeftParenthesis6505Slash160MhzRightParenthesis,
    #[serde(rename = "113 (6515/20 MHz)")]
    Variant113LeftParenthesis6515Slash20MhzRightParenthesis,
    #[serde(rename = "115 (6525/40 MHz)")]
    Variant115LeftParenthesis6525Slash40MhzRightParenthesis,
    #[serde(rename = "117 (6535/20 MHz)")]
    Variant117LeftParenthesis6535Slash20MhzRightParenthesis,
    #[serde(rename = "119 (6545/80 MHz)")]
    Variant119LeftParenthesis6545Slash80MhzRightParenthesis,
    #[serde(rename = "121 (6555/20 MHz)")]
    Variant121LeftParenthesis6555Slash20MhzRightParenthesis,
    #[serde(rename = "123 (6565/40 MHz)")]
    Variant123LeftParenthesis6565Slash40MhzRightParenthesis,
    #[serde(rename = "125 (6575/20 MHz)")]
    Variant125LeftParenthesis6575Slash20MhzRightParenthesis,
    #[serde(rename = "129 (6595/20 MHz)")]
    Variant129LeftParenthesis6595Slash20MhzRightParenthesis,
    #[serde(rename = "131 (6605/40 MHz)")]
    Variant131LeftParenthesis6605Slash40MhzRightParenthesis,
    #[serde(rename = "133 (6615/20 MHz)")]
    Variant133LeftParenthesis6615Slash20MhzRightParenthesis,
    #[serde(rename = "135 (6625/80 MHz)")]
    Variant135LeftParenthesis6625Slash80MhzRightParenthesis,
    #[serde(rename = "137 (6635/20 MHz)")]
    Variant137LeftParenthesis6635Slash20MhzRightParenthesis,
    #[serde(rename = "139 (6645/40 MHz)")]
    Variant139LeftParenthesis6645Slash40MhzRightParenthesis,
    #[serde(rename = "141 (6655/20 MHz)")]
    Variant141LeftParenthesis6655Slash20MhzRightParenthesis,
    #[serde(rename = "143 (6665/160 MHz)")]
    Variant143LeftParenthesis6665Slash160MhzRightParenthesis,
    #[serde(rename = "145 (6675/20 MHz)")]
    Variant145LeftParenthesis6675Slash20MhzRightParenthesis,
    #[serde(rename = "147 (6685/40 MHz)")]
    Variant147LeftParenthesis6685Slash40MhzRightParenthesis,
    #[serde(rename = "149 (6695/20 MHz)")]
    Variant149LeftParenthesis6695Slash20MhzRightParenthesis,
    #[serde(rename = "151 (6705/80 MHz)")]
    Variant151LeftParenthesis6705Slash80MhzRightParenthesis,
    #[serde(rename = "153 (6715/20 MHz)")]
    Variant153LeftParenthesis6715Slash20MhzRightParenthesis,
    #[serde(rename = "155 (6725/40 MHz)")]
    Variant155LeftParenthesis6725Slash40MhzRightParenthesis,
    #[serde(rename = "157 (6735/20 MHz)")]
    Variant157LeftParenthesis6735Slash20MhzRightParenthesis,
    #[serde(rename = "159 (6745/320 MHz)")]
    Variant159LeftParenthesis6745Slash320MhzRightParenthesis,
    #[serde(rename = "161 (6755/20 MHz)")]
    Variant161LeftParenthesis6755Slash20MhzRightParenthesis,
    #[serde(rename = "163 (6765/40 MHz)")]
    Variant163LeftParenthesis6765Slash40MhzRightParenthesis,
    #[serde(rename = "165 (6775/20 MHz)")]
    Variant165LeftParenthesis6775Slash20MhzRightParenthesis,
    #[serde(rename = "167 (6785/80 MHz)")]
    Variant167LeftParenthesis6785Slash80MhzRightParenthesis,
    #[serde(rename = "169 (6795/20 MHz)")]
    Variant169LeftParenthesis6795Slash20MhzRightParenthesis,
    #[serde(rename = "171 (6805/40 MHz)")]
    Variant171LeftParenthesis6805Slash40MhzRightParenthesis,
    #[serde(rename = "173 (6815/20 MHz)")]
    Variant173LeftParenthesis6815Slash20MhzRightParenthesis,
    #[serde(rename = "175 (6825/160 MHz)")]
    Variant175LeftParenthesis6825Slash160MhzRightParenthesis,
    #[serde(rename = "177 (6835/20 MHz)")]
    Variant177LeftParenthesis6835Slash20MhzRightParenthesis,
    #[serde(rename = "179 (6845/40 MHz)")]
    Variant179LeftParenthesis6845Slash40MhzRightParenthesis,
    #[serde(rename = "181 (6855/20 MHz)")]
    Variant181LeftParenthesis6855Slash20MhzRightParenthesis,
    #[serde(rename = "183 (6865/80 MHz)")]
    Variant183LeftParenthesis6865Slash80MhzRightParenthesis,
    #[serde(rename = "185 (6875/20 MHz)")]
    Variant185LeftParenthesis6875Slash20MhzRightParenthesis,
    #[serde(rename = "187 (6885/40 MHz)")]
    Variant187LeftParenthesis6885Slash40MhzRightParenthesis,
    #[serde(rename = "189 (6895/20 MHz)")]
    Variant189LeftParenthesis6895Slash20MhzRightParenthesis,
    #[serde(rename = "193 (6915/20 MHz)")]
    Variant193LeftParenthesis6915Slash20MhzRightParenthesis,
    #[serde(rename = "195 (6925/40 MHz)")]
    Variant195LeftParenthesis6925Slash40MhzRightParenthesis,
    #[serde(rename = "197 (6935/20 MHz)")]
    Variant197LeftParenthesis6935Slash20MhzRightParenthesis,
    #[serde(rename = "199 (6945/80 MHz)")]
    Variant199LeftParenthesis6945Slash80MhzRightParenthesis,
    #[serde(rename = "201 (6955/20 MHz)")]
    Variant201LeftParenthesis6955Slash20MhzRightParenthesis,
    #[serde(rename = "203 (6965/40 MHz)")]
    Variant203LeftParenthesis6965Slash40MhzRightParenthesis,
    #[serde(rename = "205 (6975/20 MHz)")]
    Variant205LeftParenthesis6975Slash20MhzRightParenthesis,
    #[serde(rename = "207 (6985/160 MHz)")]
    Variant207LeftParenthesis6985Slash160MhzRightParenthesis,
    #[serde(rename = "209 (6995/20 MHz)")]
    Variant209LeftParenthesis6995Slash20MhzRightParenthesis,
    #[serde(rename = "211 (7005/40 MHz)")]
    Variant211LeftParenthesis7005Slash40MhzRightParenthesis,
    #[serde(rename = "213 (7015/20 MHz)")]
    Variant213LeftParenthesis7015Slash20MhzRightParenthesis,
    #[serde(rename = "215 (7025/80 MHz)")]
    Variant215LeftParenthesis7025Slash80MhzRightParenthesis,
    #[serde(rename = "217 (7035/20 MHz)")]
    Variant217LeftParenthesis7035Slash20MhzRightParenthesis,
    #[serde(rename = "219 (7045/40 MHz)")]
    Variant219LeftParenthesis7045Slash40MhzRightParenthesis,
    #[serde(rename = "221 (7055/20 MHz)")]
    Variant221LeftParenthesis7055Slash20MhzRightParenthesis,
    #[serde(rename = "225 (7075/20 MHz)")]
    Variant225LeftParenthesis7075Slash20MhzRightParenthesis,
    #[serde(rename = "227 (7085/40 MHz)")]
    Variant227LeftParenthesis7085Slash40MhzRightParenthesis,
    #[serde(rename = "229 (7095/20 MHz)")]
    Variant229LeftParenthesis7095Slash20MhzRightParenthesis,
    #[serde(rename = "233 (7115/20 MHz)")]
    Variant233LeftParenthesis7115Slash20MhzRightParenthesis,
    #[serde(rename = "1 (58.32/2.16 GHz)")]
    Variant1LeftParenthesis58Period32Slash2Period16GhzRightParenthesis,
    #[serde(rename = "2 (60.48/2.16 GHz)")]
    Variant2LeftParenthesis60Period48Slash2Period16GhzRightParenthesis,
    #[serde(rename = "3 (62.64/2.16 GHz)")]
    Variant3LeftParenthesis62Period64Slash2Period16GhzRightParenthesis,
    #[serde(rename = "4 (64.80/2.16 GHz)")]
    Variant4LeftParenthesis64Period80Slash2Period16GhzRightParenthesis,
    #[serde(rename = "5 (66.96/2.16 GHz)")]
    Variant5LeftParenthesis66Period96Slash2Period16GhzRightParenthesis,
    #[serde(rename = "6 (69.12/2.16 GHz)")]
    Variant6LeftParenthesis69Period12Slash2Period16GhzRightParenthesis,
    #[serde(rename = "9 (59.40/4.32 GHz)")]
    Variant9LeftParenthesis59Period40Slash4Period32GhzRightParenthesis,
    #[serde(rename = "10 (61.56/4.32 GHz)")]
    Variant10LeftParenthesis61Period56Slash4Period32GhzRightParenthesis,
    #[serde(rename = "11 (63.72/4.32 GHz)")]
    Variant11LeftParenthesis63Period72Slash4Period32GhzRightParenthesis,
    #[serde(rename = "12 (65.88/4.32 GHz)")]
    Variant12LeftParenthesis65Period88Slash4Period32GhzRightParenthesis,
    #[serde(rename = "13 (68.04/4.32 GHz)")]
    Variant13LeftParenthesis68Period04Slash4Period32GhzRightParenthesis,
    #[serde(rename = "17 (60.48/6.48 GHz)")]
    Variant17LeftParenthesis60Period48Slash6Period48GhzRightParenthesis,
    #[serde(rename = "18 (62.64/6.48 GHz)")]
    Variant18LeftParenthesis62Period64Slash6Period48GhzRightParenthesis,
    #[serde(rename = "19 (64.80/6.48 GHz)")]
    Variant19LeftParenthesis64Period80Slash6Period48GhzRightParenthesis,
    #[serde(rename = "20 (66.96/6.48 GHz)")]
    Variant20LeftParenthesis66Period96Slash6Period48GhzRightParenthesis,
    #[serde(rename = "25 (61.56/8.64 GHz)")]
    Variant25LeftParenthesis61Period56Slash8Period64GhzRightParenthesis,
    #[serde(rename = "26 (63.72/8.64 GHz)")]
    Variant26LeftParenthesis63Period72Slash8Period64GhzRightParenthesis,
    #[serde(rename = "27 (65.88/8.64 GHz)")]
    Variant27LeftParenthesis65Period88Slash8Period64GhzRightParenthesis,
}

impl Default for Label {
    fn default() -> Label {
        Self::Variant1LeftParenthesis2412MhzRightParenthesis
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Value {
    #[serde(rename = "2.4g-1-2412-22")]
    Variant2Period4g1241222,
    #[serde(rename = "2.4g-2-2417-22")]
    Variant2Period4g2241722,
    #[serde(rename = "2.4g-3-2422-22")]
    Variant2Period4g3242222,
    #[serde(rename = "2.4g-4-2427-22")]
    Variant2Period4g4242722,
    #[serde(rename = "2.4g-5-2432-22")]
    Variant2Period4g5243222,
    #[serde(rename = "2.4g-6-2437-22")]
    Variant2Period4g6243722,
    #[serde(rename = "2.4g-7-2442-22")]
    Variant2Period4g7244222,
    #[serde(rename = "2.4g-8-2447-22")]
    Variant2Period4g8244722,
    #[serde(rename = "2.4g-9-2452-22")]
    Variant2Period4g9245222,
    #[serde(rename = "2.4g-10-2457-22")]
    Variant2Period4g10245722,
    #[serde(rename = "2.4g-11-2462-22")]
    Variant2Period4g11246222,
    #[serde(rename = "2.4g-12-2467-22")]
    Variant2Period4g12246722,
    #[serde(rename = "2.4g-13-2472-22")]
    Variant2Period4g13247222,
    #[serde(rename = "5g-32-5160-20")]
    Variant5g32516020,
    #[serde(rename = "5g-34-5170-40")]
    Variant5g34517040,
    #[serde(rename = "5g-36-5180-20")]
    Variant5g36518020,
    #[serde(rename = "5g-38-5190-40")]
    Variant5g38519040,
    #[serde(rename = "5g-40-5200-20")]
    Variant5g40520020,
    #[serde(rename = "5g-42-5210-80")]
    Variant5g42521080,
    #[serde(rename = "5g-44-5220-20")]
    Variant5g44522020,
    #[serde(rename = "5g-46-5230-40")]
    Variant5g46523040,
    #[serde(rename = "5g-48-5240-20")]
    Variant5g48524020,
    #[serde(rename = "5g-50-5250-160")]
    Variant5g505250160,
    #[serde(rename = "5g-52-5260-20")]
    Variant5g52526020,
    #[serde(rename = "5g-54-5270-40")]
    Variant5g54527040,
    #[serde(rename = "5g-56-5280-20")]
    Variant5g56528020,
    #[serde(rename = "5g-58-5290-80")]
    Variant5g58529080,
    #[serde(rename = "5g-60-5300-20")]
    Variant5g60530020,
    #[serde(rename = "5g-62-5310-40")]
    Variant5g62531040,
    #[serde(rename = "5g-64-5320-20")]
    Variant5g64532020,
    #[serde(rename = "5g-100-5500-20")]
    Variant5g100550020,
    #[serde(rename = "5g-102-5510-40")]
    Variant5g102551040,
    #[serde(rename = "5g-104-5520-20")]
    Variant5g104552020,
    #[serde(rename = "5g-106-5530-80")]
    Variant5g106553080,
    #[serde(rename = "5g-108-5540-20")]
    Variant5g108554020,
    #[serde(rename = "5g-110-5550-40")]
    Variant5g110555040,
    #[serde(rename = "5g-112-5560-20")]
    Variant5g112556020,
    #[serde(rename = "5g-114-5570-160")]
    Variant5g1145570160,
    #[serde(rename = "5g-116-5580-20")]
    Variant5g116558020,
    #[serde(rename = "5g-118-5590-40")]
    Variant5g118559040,
    #[serde(rename = "5g-120-5600-20")]
    Variant5g120560020,
    #[serde(rename = "5g-122-5610-80")]
    Variant5g122561080,
    #[serde(rename = "5g-124-5620-20")]
    Variant5g124562020,
    #[serde(rename = "5g-126-5630-40")]
    Variant5g126563040,
    #[serde(rename = "5g-128-5640-20")]
    Variant5g128564020,
    #[serde(rename = "5g-132-5660-20")]
    Variant5g132566020,
    #[serde(rename = "5g-134-5670-40")]
    Variant5g134567040,
    #[serde(rename = "5g-136-5680-20")]
    Variant5g136568020,
    #[serde(rename = "5g-138-5690-80")]
    Variant5g138569080,
    #[serde(rename = "5g-140-5700-20")]
    Variant5g140570020,
    #[serde(rename = "5g-142-5710-40")]
    Variant5g142571040,
    #[serde(rename = "5g-144-5720-20")]
    Variant5g144572020,
    #[serde(rename = "5g-149-5745-20")]
    Variant5g149574520,
    #[serde(rename = "5g-151-5755-40")]
    Variant5g151575540,
    #[serde(rename = "5g-153-5765-20")]
    Variant5g153576520,
    #[serde(rename = "5g-155-5775-80")]
    Variant5g155577580,
    #[serde(rename = "5g-157-5785-20")]
    Variant5g157578520,
    #[serde(rename = "5g-159-5795-40")]
    Variant5g159579540,
    #[serde(rename = "5g-161-5805-20")]
    Variant5g161580520,
    #[serde(rename = "5g-163-5815-160")]
    Variant5g1635815160,
    #[serde(rename = "5g-165-5825-20")]
    Variant5g165582520,
    #[serde(rename = "5g-167-5835-40")]
    Variant5g167583540,
    #[serde(rename = "5g-169-5845-20")]
    Variant5g169584520,
    #[serde(rename = "5g-171-5855-80")]
    Variant5g171585580,
    #[serde(rename = "5g-173-5865-20")]
    Variant5g173586520,
    #[serde(rename = "5g-175-5875-40")]
    Variant5g175587540,
    #[serde(rename = "5g-177-5885-20")]
    Variant5g177588520,
    #[serde(rename = "6g-1-5955-20")]
    Variant6g1595520,
    #[serde(rename = "6g-3-5965-40")]
    Variant6g3596540,
    #[serde(rename = "6g-5-5975-20")]
    Variant6g5597520,
    #[serde(rename = "6g-7-5985-80")]
    Variant6g7598580,
    #[serde(rename = "6g-9-5995-20")]
    Variant6g9599520,
    #[serde(rename = "6g-11-6005-40")]
    Variant6g11600540,
    #[serde(rename = "6g-13-6015-20")]
    Variant6g13601520,
    #[serde(rename = "6g-15-6025-160")]
    Variant6g156025160,
    #[serde(rename = "6g-17-6035-20")]
    Variant6g17603520,
    #[serde(rename = "6g-19-6045-40")]
    Variant6g19604540,
    #[serde(rename = "6g-21-6055-20")]
    Variant6g21605520,
    #[serde(rename = "6g-23-6065-80")]
    Variant6g23606580,
    #[serde(rename = "6g-25-6075-20")]
    Variant6g25607520,
    #[serde(rename = "6g-27-6085-40")]
    Variant6g27608540,
    #[serde(rename = "6g-29-6095-20")]
    Variant6g29609520,
    #[serde(rename = "6g-31-6105-320")]
    Variant6g316105320,
    #[serde(rename = "6g-33-6115-20")]
    Variant6g33611520,
    #[serde(rename = "6g-35-6125-40")]
    Variant6g35612540,
    #[serde(rename = "6g-37-6135-20")]
    Variant6g37613520,
    #[serde(rename = "6g-39-6145-80")]
    Variant6g39614580,
    #[serde(rename = "6g-41-6155-20")]
    Variant6g41615520,
    #[serde(rename = "6g-43-6165-40")]
    Variant6g43616540,
    #[serde(rename = "6g-45-6175-20")]
    Variant6g45617520,
    #[serde(rename = "6g-47-6185-160")]
    Variant6g476185160,
    #[serde(rename = "6g-49-6195-20")]
    Variant6g49619520,
    #[serde(rename = "6g-51-6205-40")]
    Variant6g51620540,
    #[serde(rename = "6g-53-6215-20")]
    Variant6g53621520,
    #[serde(rename = "6g-55-6225-80")]
    Variant6g55622580,
    #[serde(rename = "6g-57-6235-20")]
    Variant6g57623520,
    #[serde(rename = "6g-59-6245-40")]
    Variant6g59624540,
    #[serde(rename = "6g-61-6255-20")]
    Variant6g61625520,
    #[serde(rename = "6g-65-6275-20")]
    Variant6g65627520,
    #[serde(rename = "6g-67-6285-40")]
    Variant6g67628540,
    #[serde(rename = "6g-69-6295-20")]
    Variant6g69629520,
    #[serde(rename = "6g-71-6305-80")]
    Variant6g71630580,
    #[serde(rename = "6g-73-6315-20")]
    Variant6g73631520,
    #[serde(rename = "6g-75-6325-40")]
    Variant6g75632540,
    #[serde(rename = "6g-77-6335-20")]
    Variant6g77633520,
    #[serde(rename = "6g-79-6345-160")]
    Variant6g796345160,
    #[serde(rename = "6g-81-6355-20")]
    Variant6g81635520,
    #[serde(rename = "6g-83-6365-40")]
    Variant6g83636540,
    #[serde(rename = "6g-85-6375-20")]
    Variant6g85637520,
    #[serde(rename = "6g-87-6385-80")]
    Variant6g87638580,
    #[serde(rename = "6g-89-6395-20")]
    Variant6g89639520,
    #[serde(rename = "6g-91-6405-40")]
    Variant6g91640540,
    #[serde(rename = "6g-93-6415-20")]
    Variant6g93641520,
    #[serde(rename = "6g-95-6425-320")]
    Variant6g956425320,
    #[serde(rename = "6g-97-6435-20")]
    Variant6g97643520,
    #[serde(rename = "6g-99-6445-40")]
    Variant6g99644540,
    #[serde(rename = "6g-101-6455-20")]
    Variant6g101645520,
    #[serde(rename = "6g-103-6465-80")]
    Variant6g103646580,
    #[serde(rename = "6g-105-6475-20")]
    Variant6g105647520,
    #[serde(rename = "6g-107-6485-40")]
    Variant6g107648540,
    #[serde(rename = "6g-109-6495-20")]
    Variant6g109649520,
    #[serde(rename = "6g-111-6505-160")]
    Variant6g1116505160,
    #[serde(rename = "6g-113-6515-20")]
    Variant6g113651520,
    #[serde(rename = "6g-115-6525-40")]
    Variant6g115652540,
    #[serde(rename = "6g-117-6535-20")]
    Variant6g117653520,
    #[serde(rename = "6g-119-6545-80")]
    Variant6g119654580,
    #[serde(rename = "6g-121-6555-20")]
    Variant6g121655520,
    #[serde(rename = "6g-123-6565-40")]
    Variant6g123656540,
    #[serde(rename = "6g-125-6575-20")]
    Variant6g125657520,
    #[serde(rename = "6g-129-6595-20")]
    Variant6g129659520,
    #[serde(rename = "6g-131-6605-40")]
    Variant6g131660540,
    #[serde(rename = "6g-133-6615-20")]
    Variant6g133661520,
    #[serde(rename = "6g-135-6625-80")]
    Variant6g135662580,
    #[serde(rename = "6g-137-6635-20")]
    Variant6g137663520,
    #[serde(rename = "6g-139-6645-40")]
    Variant6g139664540,
    #[serde(rename = "6g-141-6655-20")]
    Variant6g141665520,
    #[serde(rename = "6g-143-6665-160")]
    Variant6g1436665160,
    #[serde(rename = "6g-145-6675-20")]
    Variant6g145667520,
    #[serde(rename = "6g-147-6685-40")]
    Variant6g147668540,
    #[serde(rename = "6g-149-6695-20")]
    Variant6g149669520,
    #[serde(rename = "6g-151-6705-80")]
    Variant6g151670580,
    #[serde(rename = "6g-153-6715-20")]
    Variant6g153671520,
    #[serde(rename = "6g-155-6725-40")]
    Variant6g155672540,
    #[serde(rename = "6g-157-6735-20")]
    Variant6g157673520,
    #[serde(rename = "6g-159-6745-320")]
    Variant6g1596745320,
    #[serde(rename = "6g-161-6755-20")]
    Variant6g161675520,
    #[serde(rename = "6g-163-6765-40")]
    Variant6g163676540,
    #[serde(rename = "6g-165-6775-20")]
    Variant6g165677520,
    #[serde(rename = "6g-167-6785-80")]
    Variant6g167678580,
    #[serde(rename = "6g-169-6795-20")]
    Variant6g169679520,
    #[serde(rename = "6g-171-6805-40")]
    Variant6g171680540,
    #[serde(rename = "6g-173-6815-20")]
    Variant6g173681520,
    #[serde(rename = "6g-175-6825-160")]
    Variant6g1756825160,
    #[serde(rename = "6g-177-6835-20")]
    Variant6g177683520,
    #[serde(rename = "6g-179-6845-40")]
    Variant6g179684540,
    #[serde(rename = "6g-181-6855-20")]
    Variant6g181685520,
    #[serde(rename = "6g-183-6865-80")]
    Variant6g183686580,
    #[serde(rename = "6g-185-6875-20")]
    Variant6g185687520,
    #[serde(rename = "6g-187-6885-40")]
    Variant6g187688540,
    #[serde(rename = "6g-189-6895-20")]
    Variant6g189689520,
    #[serde(rename = "6g-193-6915-20")]
    Variant6g193691520,
    #[serde(rename = "6g-195-6925-40")]
    Variant6g195692540,
    #[serde(rename = "6g-197-6935-20")]
    Variant6g197693520,
    #[serde(rename = "6g-199-6945-80")]
    Variant6g199694580,
    #[serde(rename = "6g-201-6955-20")]
    Variant6g201695520,
    #[serde(rename = "6g-203-6965-40")]
    Variant6g203696540,
    #[serde(rename = "6g-205-6975-20")]
    Variant6g205697520,
    #[serde(rename = "6g-207-6985-160")]
    Variant6g2076985160,
    #[serde(rename = "6g-209-6995-20")]
    Variant6g209699520,
    #[serde(rename = "6g-211-7005-40")]
    Variant6g211700540,
    #[serde(rename = "6g-213-7015-20")]
    Variant6g213701520,
    #[serde(rename = "6g-215-7025-80")]
    Variant6g215702580,
    #[serde(rename = "6g-217-7035-20")]
    Variant6g217703520,
    #[serde(rename = "6g-219-7045-40")]
    Variant6g219704540,
    #[serde(rename = "6g-221-7055-20")]
    Variant6g221705520,
    #[serde(rename = "6g-225-7075-20")]
    Variant6g225707520,
    #[serde(rename = "6g-227-7085-40")]
    Variant6g227708540,
    #[serde(rename = "6g-229-7095-20")]
    Variant6g229709520,
    #[serde(rename = "6g-233-7115-20")]
    Variant6g233711520,
    #[serde(rename = "60g-1-58320-2160")]
    Variant60g1583202160,
    #[serde(rename = "60g-2-60480-2160")]
    Variant60g2604802160,
    #[serde(rename = "60g-3-62640-2160")]
    Variant60g3626402160,
    #[serde(rename = "60g-4-64800-2160")]
    Variant60g4648002160,
    #[serde(rename = "60g-5-66960-2160")]
    Variant60g5669602160,
    #[serde(rename = "60g-6-69120-2160")]
    Variant60g6691202160,
    #[serde(rename = "60g-9-59400-4320")]
    Variant60g9594004320,
    #[serde(rename = "60g-10-61560-4320")]
    Variant60g10615604320,
    #[serde(rename = "60g-11-63720-4320")]
    Variant60g11637204320,
    #[serde(rename = "60g-12-65880-4320")]
    Variant60g12658804320,
    #[serde(rename = "60g-13-68040-4320")]
    Variant60g13680404320,
    #[serde(rename = "60g-17-60480-6480")]
    Variant60g17604806480,
    #[serde(rename = "60g-18-62640-6480")]
    Variant60g18626406480,
    #[serde(rename = "60g-19-64800-6480")]
    Variant60g19648006480,
    #[serde(rename = "60g-20-66960-6480")]
    Variant60g20669606480,
    #[serde(rename = "60g-25-61560-6480")]
    Variant60g25615606480,
    #[serde(rename = "60g-26-63720-6480")]
    Variant60g26637206480,
    #[serde(rename = "60g-27-65880-6480")]
    Variant60g27658806480,
}

impl Default for Value {
    fn default() -> Value {
        Self::Variant2Period4g1241222
    }
}

