/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Status7 {
    #[serde(rename = "label")]
    pub label: Label,
    #[serde(rename = "value")]
    pub value: Value,
}

impl Status7 {
    pub fn new(label: Label, value: Value) -> Status7 {
        Status7 {
            label,
            value,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Label {
    #[serde(rename = "Active")]
    Active,
    #[serde(rename = "Reserved")]
    Reserved,
    #[serde(rename = "Deprecated")]
    Deprecated,
    #[serde(rename = "DHCP")]
    Dhcp,
    #[serde(rename = "SLAAC")]
    Slaac,
}

impl Default for Label {
    fn default() -> Label {
        Self::Active
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Value {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "reserved")]
    Reserved,
    #[serde(rename = "deprecated")]
    Deprecated,
    #[serde(rename = "dhcp")]
    Dhcp,
    #[serde(rename = "slaac")]
    Slaac,
}

impl Default for Value {
    fn default() -> Value {
        Self::Active
    }
}

