/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UiVisibility {
    #[serde(rename = "label")]
    pub label: Label,
    #[serde(rename = "value")]
    pub value: Value,
}

impl UiVisibility {
    pub fn new(label: Label, value: Value) -> UiVisibility {
        UiVisibility {
            label,
            value,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Label {
    #[serde(rename = "Read/Write")]
    ReadSlashWrite,
    #[serde(rename = "Read-only")]
    ReadOnly,
    #[serde(rename = "Hidden")]
    Hidden,
}

impl Default for Label {
    fn default() -> Label {
        Self::ReadSlashWrite
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Value {
    #[serde(rename = "read-write")]
    ReadWrite,
    #[serde(rename = "read-only")]
    ReadOnly,
    #[serde(rename = "hidden")]
    Hidden,
}

impl Default for Value {
    fn default() -> Value {
        Self::ReadWrite
    }
}

