/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WritableContactAssignment {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "content_type")]
    pub content_type: String,
    #[serde(rename = "object_id")]
    pub object_id: i32,
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<serde_json::Value>,
    #[serde(rename = "contact")]
    pub contact: i32,
    #[serde(rename = "role")]
    pub role: i32,
    #[serde(rename = "priority")]
    pub priority: Priority,
    #[serde(rename = "created", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub created: Option<Option<String>>,
    #[serde(rename = "last_updated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<Option<String>>,
}

impl WritableContactAssignment {
    pub fn new(content_type: String, object_id: i32, contact: i32, role: i32, priority: Priority) -> WritableContactAssignment {
        WritableContactAssignment {
            id: None,
            url: None,
            display: None,
            content_type,
            object_id,
            object: None,
            contact,
            role,
            priority,
            created: None,
            last_updated: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Priority {
    #[serde(rename = "primary")]
    Primary,
    #[serde(rename = "secondary")]
    Secondary,
    #[serde(rename = "tertiary")]
    Tertiary,
    #[serde(rename = "inactive")]
    Inactive,
}

impl Default for Priority {
    fn default() -> Priority {
        Self::Primary
    }
}

