/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Width {
    #[serde(rename = "label")]
    pub label: Label,
    #[serde(rename = "value")]
    pub value: i32,
}

impl Width {
    pub fn new(label: Label, value: i32) -> Width {
        Width {
            label,
            value,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Label {
    #[serde(rename = "10 inches")]
    Variant10Inches,
    #[serde(rename = "19 inches")]
    Variant19Inches,
    #[serde(rename = "21 inches")]
    Variant21Inches,
    #[serde(rename = "23 inches")]
    Variant23Inches,
}

impl Default for Label {
    fn default() -> Label {
        Self::Variant10Inches
    }
}

