/*
 * NetBox API
 *
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WritableCircuit {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "cid")]
    pub cid: String,
    #[serde(rename = "provider")]
    pub provider: i32,
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "tenant", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant: Option<Option<i32>>,
    #[serde(rename = "install_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub install_date: Option<Option<String>>,
    #[serde(rename = "termination_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub termination_date: Option<Option<String>>,
    #[serde(rename = "commit_rate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub commit_rate: Option<Option<i32>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "termination_a", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub termination_a: Option<Option<i32>>,
    #[serde(rename = "termination_z", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub termination_z: Option<Option<i32>>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTag>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<serde_json::Value>,
    #[serde(rename = "created", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub created: Option<Option<String>>,
    #[serde(rename = "last_updated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<Option<String>>,
}

impl WritableCircuit {
    pub fn new(cid: String, provider: i32, r#type: i32) -> WritableCircuit {
        WritableCircuit {
            id: None,
            url: None,
            display: None,
            cid,
            provider,
            r#type,
            status: None,
            tenant: None,
            install_date: None,
            termination_date: None,
            commit_rate: None,
            description: None,
            termination_a: None,
            termination_z: None,
            comments: None,
            tags: None,
            custom_fields: None,
            created: None,
            last_updated: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "planned")]
    Planned,
    #[serde(rename = "provisioning")]
    Provisioning,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "offline")]
    Offline,
    #[serde(rename = "deprovisioning")]
    Deprovisioning,
    #[serde(rename = "decommissioned")]
    Decommissioned,
}

impl Default for Status {
    fn default() -> Status {
        Self::Planned
    }
}

