when:
  event:
    - manual
    - release

steps:
  - name: build-docs
    image: codeberg.org/nazara-project/actions/mdbook-ci-nazara:0.4.51
    commands:
      - git fetch origin main --depth=2 || git fetch origin main --unshallow
      - git checkout main

      - mdbook build docs

  - name: deploy-pages
    image: codeberg.org/xfix/plugin-codeberg-pages-deploy:1
    depends_on:
      - build-docs
    settings:
      folder: docs/book
      ssh_key:
        from_secret: deploy-key
