steps:
  - name: build-docs
    image: codeberg.org/nazara-project/actions/mdbook-ci-nazara:0.4.51
    when:
      branch:
        - main
      event:
        - push
        - manual
    commands:
      - git fetch origin main --depth=2 || git fetch origin main --unshallow
      - |
        if [ "$WOODPECKER_EVENT" != "manual" ]; then
          if ! git diff --name-only origin/main~1..HEAD | grep -qE '^docs/'; then
            echo "No changes in docs/, skipping pipeline"
            exit 0
          fi
        fi
      - mdbook build docs

  - name: deploy-pages
    image: codeberg.org/xfix/plugin-codeberg-pages-deploy:1
    when:
      branch:
        - main
      event:
        - push
        - manual
    settings:
      folder: docs/book
      ssh_key:
        from_secret: deploy-key
