name: Dependency Vulnerability Audit

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    schedule:
        - cron: '0 0 * * 0'

jobs:
    vulnerability_audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                override: true
            - uses: actions-rs/cargo@v1
              with:
                use-cross: true
                command: install
                args: cargo-audit --locked
            - uses: actions-rs/cargo@v1
              with:
                use-cross: true
                command: audit
                args: --color always
